[v2] 타입스크립트
the-road-to-learn-react/the-road-to-react-korean pull request #1
Opened 2020-03-21 14:03 UTC by yeseulo

- TypeScript는 '타입스크립트'로 사용했습니다.
- Feedback loop를 '피드백 루프' 라고 그대로 바꿔썼는데 더 좋은 의미 풀이가 있다면 제안해주세요.
- error는 '오류', arguments는 '인수'로 사용했습니다.
- Hooks는 리액트 레거시 v2를 따라 '훅'으로 쓰고, custom hook은 '사용자 정의 훅'으로 표현했습니다.
- 타입, 정적 타입 언어, 동적 타입 언어, 의존성, 사용자 정의 훅, 인터페이스, 유니온 타입 등은 괄호에 영문을 병기했습니다.
- type safety는 '타입 안전성'으로 썼습니다.
  - 관련해서 '안전성을 높이다', '안전하게 만들다', '안전성을 확인하다'와 같은 표현을 사용했습니다.
- 역시 원문 표현을 많이 바꿨습니다. 어색한 표현이 있다면 말씀해주세요.

2020-03-21 14:10 UTC, sujinleeme approved these changes
멋진 번역 감사합니다! ❣️

2020-03-25 12:26 UTC, sujinleeme requested changes

2020-03-25 12:26 UTC, sujinleeme commented on manuscript/react-maintenance/typescript.md
> +* [React + TypeScript Cheatsheet](https://github.com/typescript-cheatsheets/react-typescript-cheatsheet#reacttypescript-cheatsheets)를 살펴보세요. 이 장에서 보았던 가장 일반적인 사용 예시도 다룹니다. 당장 이해하지 못해도 상관 습니다.
상관 습니다. 오타가 있어요.

2020-03-25 12:26 UTC, sujinleeme commented on manuscript/react-maintenance/typescript.md
> +리액트에서 타입스크립트를 사용하기 위해, 커맨드 라인에서 애플리케이션에 타입스크립트와 해당 의존성(dependencies)을 설치하세요. 설치 과정에서 막히면 [create-react-app](https://create-react-app.dev/docs/adding-typescript/)의 공식 타입스크립트 설치 지침을 따르세요.
dependencies는 삭제해도 될 것 같아요.

2020-03-25 12:26 UTC, sujinleeme commented on manuscript/react-maintenance/typescript.md
> +커맨드 라인에서 개발 서버를 다시 시작하세요. 브라우저와 IDE에서 컴파일 오류가 발생할 수 있습니다. 동작하지 않는다면 에디터에 타입스크립트 플러그인이나 IDE의 확장 기능을 설치해보세요. 리액트에서 타입스크립트를 설정한 뒤, 사용자 정의 훅(custom hook)의 인수(arguments)에 타입을 지정하여 전체 *src/App.tsx* 파일에 대한
사용자 정의 훅(custom hook)의 인수(arguments) 인수 뒤에 arguments, 그리고 type safety는 삭제해도 될 것 같아요.

2020-03-27 06:25 UTC, yeseulo commented
세 가지 모두 수정했습니다!

2020-03-27 07:18 UTC, merged