V2 react modern advanced
the-road-to-learn-react/the-road-to-react-korean pull request #10
Opened 2020-04-01 12:07 UTC by yyijoo

2020-04-02 12:06 UTC, sujinleeme requested changes

2020-04-02 12:06 UTC, sujinleeme commented on manuscript/react-modern-advanced/paginated-fetch.md
> +### 연습문제:
실습하기 로 수정해주세요. (:)는 빼주세요.

2020-04-02 12:06 UTC, sujinleeme commented on manuscript/react-modern-advanced/paginated-fetch.md
> +이제 인기있는 기사 데이터를 계속해서 불러올 수 있습니다. 외부 API를 활용할 때는 항상 해당 API로 작업 가능한 범위를 알아두는 것이 좋습니다. 외부 API는 각기 다른 데이터 구조로 되어있어 특징도 다릅니다. (번역자: 마지막 문장은... 의미를 잘 모르겠어서 skip 합니다.)
외부 API마다 데이터 구조와 기능도 서로 다르다는 것을 기억하세요. 
 어떨까요?

2020-04-02 12:07 UTC, sujinleeme commented on manuscript/react-modern-advanced/remember-last-searches.md
> +**과제:** API 요청을 할 수 있도록 최근 검색어 5개를 저장하고 검색어간 쉽게 이동할 수 있는 버튼을 추가합니다. 버튼을 클릭하면 검색어에 맞는 책 검색 결과를 다시 요청해 받아올 수 있도록 합니다.
과제 뒤에 : 삭제해주세요.

2020-04-04 10:36 UTC, sujinleeme requested changes

2020-04-04 10:36 UTC, sujinleeme commented on manuscript/react-modern-advanced/sorting.md
> +### 연습문제:
뒤에: 삭제해주세요

2020-04-04 10:36 UTC, sujinleeme commented on manuscript/react-modern-advanced/sorting.md
> +**과제:** 여러 아이템을 담은 목록을 다룰 때는 사용자가 효율적으로 데이터를 탐색할 수 있도록 작업 해야 하는 경우가 많습니다. 지금까지 모든 아이템을 각각의 속성들과 함께 나열했습니다. 사용자가 데이터를 더 쉽게 탐색하려면 목록을 제목, 저자, 댓글, 점수로 오름차순 및 내림차순 정렬할 수 있어야 합니다. 오름차순이나 내림차순 한 방향으로만 정렬을
뒤에 : 를 삭제해주세요.

2020-04-04 10:36 UTC, sujinleeme commented on manuscript/react-modern-advanced/reverse-sort.md
> +### 연습문제:
인스턴스

2020-04-04 10:36 UTC, sujinleeme commented on manuscript/react-modern-advanced/reverse-sort.md
> +**힌트 보기:**
뒤에 :를 삭제해주세요.

2020-04-04 10:36 UTC, sujinleeme commented on manuscript/react-modern-advanced/remember-last-searches.md
> +### 연습문제:
뒤에 :를 삭제해주세요.

2020-04-04 10:36 UTC, sujinleeme commented on manuscript/react-modern-advanced/remember-last-searches.md
> +**추가 과제:**
뒤에 :를 삭제해주세요.

2020-04-05 23:07 UTC, yyijoo commented on manuscript/react-modern-advanced/paginated-fetch.md
> +### 연습문제:
연습문제:를 모두 '실습하기'로 수정 반영할게요!

2020-04-05 23:16 UTC, yyijoo commented on manuscript/react-modern-advanced/remember-last-searches.md
> +**추가 과제:**
반영했습니다!

2020-04-05 23:16 UTC, yyijoo commented on manuscript/react-modern-advanced/remember-last-searches.md
> +### 연습문제:
반영했습니다!

2020-04-05 23:16 UTC, yyijoo commented on manuscript/react-modern-advanced/reverse-sort.md
> +**힌트 보기:**
반영했습니다!

2020-04-05 23:16 UTC, yyijoo commented on manuscript/react-modern-advanced/reverse-sort.md
> +### 연습문제:
위 연습문제 피드백과 동일하게 실습하기로 바꾸었습니다!

2020-04-05 23:17 UTC, yyijoo commented on manuscript/react-modern-advanced/paginated-fetch.md
> +이제 인기있는 기사 데이터를 계속해서 불러올 수 있습니다. 외부 API를 활용할 때는 항상 해당 API로 작업 가능한 범위를 알아두는 것이 좋습니다. 외부 API는 각기 다른 데이터 구조로 되어있어 특징도 다릅니다. (번역자: 마지막 문장은... 의미를 잘 모르겠어서 skip 합니다.)
반영했습니다!

2020-04-05 23:17 UTC, yyijoo commented on manuscript/react-modern-advanced/remember-last-searches.md
> +**과제:** API 요청을 할 수 있도록 최근 검색어 5개를 저장하고 검색어간 쉽게 이동할 수 있는 버튼을 추가합니다. 버튼을 클릭하면 검색어에 맞는 책 검색 결과를 다시 요청해 받아올 수 있도록 합니다.
반영했습니다!

2020-04-05 23:18 UTC, yyijoo commented on manuscript/react-modern-advanced/sorting.md
> +### 연습문제:
위 연습문제 피드백과 동일하게 실습하기로 바꾸었습니다!

2020-04-09 15:32 UTC, merged

2020-04-09 15:32 UTC, sujinleeme commented on manuscript/react-modern-advanced/remember-last-searches.md
> +**추가 과제:**
머지했어요 감사합니다!