[V2] css
the-road-to-learn-react/the-road-to-react-korean pull request #13
Opened 2020-04-05 11:02 UTC by haesookim

이전 레포 PR에서 변경 요청된 사항들을 반영 후 수정했습니다.

2020-04-06 04:47 UTC, sujinleeme commented on manuscript/react-styling/css.md
> +리액트 어플리케이션을 스타일링하는 데에는 여러 방법이 있고, 어떤 **스타일링 방식**이 가장 적절한지, 어떤 **접근**이 가장 효율적인지 등에는 여러 의견이 있습니다. 본문에서는 다양한 접근을 가볍게 한 번 다뤄보도록 하겠습니다. 찬성 의견도 있을 수 있고, 반대 의견도 있을 수 있겠지만, 각 개발자와 팀에게 무엇이 가장 잘 맞는지가 가장 중요합니다.
리액트 어플리케이션을 -> 애플리케이션으로 수정해주세요.

2020-04-06 04:48 UTC, sujinleeme requested changes
하나만 수정 부탁드립니다. 수고 많이 하셨어요!

2020-04-13 14:39 UTC, yeseulo commented on manuscript/react-styling/css.md
> +만약 버튼이나 대화창, 드롭다운 등의 일반적인 UI 컴포넌트를 직접 만들고 싶지 않다면, 이런 컴포넌트를 기본으로 제공하는 [UI 라이브러리](https://www.robinwieruch.de/react-libraries)를 사용하는 것도 좋은 방법입니다. 그러나, 리액트를 배우는 데에는 이런 솔루션을 활용하는 것보다는 직접 컴포넌트를 만들어보는 것이 더
그러나와 이에 뒤에 쉼표를 사용하지 않는 것이 국문에서는 더 자연스러울 것 같습니다.

2020-04-13 14:39 UTC, yeseulo commented on manuscript/react-styling/css.md
> +후술할 스타일링 방법론과 SVG들은 `create-react-app`에 미리 설정되어 있습니다. 만약 Webpack 등의 빌드 툴을 활용하고 있다면, CSS나 SVG 파일을 불러오기 위해서 따로 설정을 해 줘야 할 수도 있습니다. 우리는 create-react-app을 사용할 것이기 때문에, 기존에 있던 파일들을 사용하면 됩니다.
설정을 해 줘야 할 수도 → 설정을 해야 할 수도

2020-04-13 14:41 UTC, yeseulo commented on manuscript/react-styling/css.md
> +이전 컴포넌트에서의 버튼 스타일을 아직 정의하지 않았기 때문에, 여기에서 우리는 기본적인 버튼 스타일과 두 개의 더 구체적인 버튼 디자인 (작은 버튼과 큰 버튼)을 정의하도록 하겠습니다. 둘 중 하나는 이미 사용되었고, 나머지 하나는 앞으로 쓸 예정입니다.
둘 중 하나는 이미 사용되었고 → 둘 중 하나는 이미 사용했고

2020-04-13 14:43 UTC, yeseulo commented on manuscript/react-styling/css.md
> +이 경우에는 코드를 단순화시키기 위해 *src/App.css* 파일에서 label이나 input과 같은 HTML 요소들을 개별적으로 스타일링했습니다. 그러나 실제 애플리케이션을 개발할 때는 *src/index.css* 파일에서 전역적으로 이와 같은 요소들을 스타일링하는 것이 더 좋을 수도 있습니다. 리액트 컴포넌트는 여러 파일에 나눠져 있기 때문에, 스타
나눠져 → 나뉘어

2020-04-15 13:14 UTC, merged