[V2] testing
the-road-to-learn-react/the-road-to-react-korean pull request #14
Opened 2020-04-05 11:05 UTC by haesookim

테스팅 관련 부분 번역 완료했습니다.
* Jest나 axios 등 라이브러리 이름은 번역하지 않고 그대로 유지했습니다
* 테스트 명칭을 일단 통일하여 번역했으나, 원어를 유지하는 편이 낫거나 더 좋은 용어가 있다면 추천 부탁드립니다.
  * E2E (End-to-end) 테스트 -> 종단간 테스트
  * integration 테스트 -> 통합 테스트
  * unit 테스트 -> 유닛 테스트
  * assertion -> 단언
  * 테스트 스위트 -> 테스트 스위트

2020-04-06 04:50 UTC, sujinleeme requested changes
일부만 수정 부탁드립니다. 깔끔한 번역 감사해요!

2020-04-06 04:50 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +Jest의 테스트는 기본적인 상위 구조인 **테스트 스위트** (`describe`)로 이루어져 있고, 각각의 스위트는 **테스트 케이스** (`it`)의 집합으로 구성되며, 각각의 테스트 케이스는 다시 여러 **단언** (`expect`)으로 나뉩니다. 테스트 실행 시 빨간색이나 초록색으로 결과를 표시합니다.
각 용어를 괄호로 남겨주시겠어요?
테스트 스위트(test suites)...

2020-04-06 04:50 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +컴포넌트를 테스팅하려면 먼저 *src/App.js* 파일에서 작성한 컴포넌트들을 export해주어야 합니다.
export 를 내보내야 합니다로 수정해주세요.

2020-04-06 04:50 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +Item 컴포넌트의 첫 번째 컴포넌트 테스트를 작성합니다. 이 테스트 케이스는 유틸리티 라이브러리를 사용하여, 특정 `item`을 기반으로 컴포넌트를 렌더링 합니다.
Item 컴포넌트의 첫 번째 컴포넌트 테스트를 작성하겠습니다 로 고쳐주세요.

2020-04-06 04:50 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +이미 [테스팅 라이브러리들](https://www.robinwieruch.de/react-testing-tutorial)이 많이 존재하기 때문에, 리액트 초심자들은 사용할 라이브러리를 고르는 데 어려움을 겪을 수도 있습니다. 우리는 이 튜토리얼에서 너무 강한 의견을 피력하는 것을 피하기 위해, 페이스북에서 개발한 [Jest](https://jestjs.i
이미 많은 [테스팅 라이브러리](https://www.robinwieruch.de/react-testing-tutorial)이 존재하기 때문에 로 수정해주세요.

2020-04-06 04:50 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +### 실습하기:
뒤에 :를 삭제해주세요.

2020-04-06 04:50 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +  * 유닛 테스트, 통합 테스트, 스냅샷 테스트에 더 알아보기 위해 [Jest](https://jestjs.io/) 와 [Jest for React](https://www.robinwieruch.de/react-testing-jest/)를 활용할 수 있습니다.
Jest for React 번역해주세요.

2020-04-13 14:23 UTC, yeseulo commented on manuscript/react-maintenance/testing.md
> +유닛 테스트는 여러 함수와 컴포넌트를 모두 테스트해야 하니, 많은 수가 필요합니다. 그 다음에는, 가장 중요한 함수와 컴포넌트들이 함께 잘 작동하는지 확인하기 위해 통합 테스트를 사용합니다. 마지막으로 우리는 몇 가지 중요한 시나리오를 모방해 보기 위해 몇 개의 종단간 테스트를 작성할 필요가 있을 수도 있습니다. 이 학습 경험에서는 **유닛 테스트와 통합
좀 더 자연스러운 표현을 생각해봤습니다.
- 종단간 테스트를 작성할 필요가 있을 수도 있습니다 → 종단간 테스트를 작성해야 할 수도 있습니다
- 이 학습 경험에서는 → 이번 학습에서는
- exercise 는 문서 하단의 '실습하기'를 이야기하는 것 같습니다.

2020-04-13 14:24 UTC, yeseulo commented on manuscript/react-maintenance/testing.md
> +유닛 테스트와 통합 테스트의 차이를 구분하기 어려운 경우도 여럿 있습니다. 예를 들어, Item 컴포넌트를 담고 있는 List 컴포넌트를 테스팅하고자 한다면, 이는 통합 테스트라고 볼 수도 있겠지만, 밀접하게 연관된 두 개의 컴포넌트 사이의 유닛 테스트일 수도 있겠죠. 이 섹션에서는 유닛 테스트에서 시작해서, 통합 테스트를 향해 나아가 보도록 하겠습니다.
한 문장에 쉼표가 여러 번 등장해서 한두 개로 줄이면 자연스러울 듯합니다.

2020-04-13 14:25 UTC, yeseulo commented on manuscript/react-maintenance/testing.md
> +다행히도 create-react-app에는 Jest가 미리 설치되어 있기 때문에, 커맨드 라인에서 create-react-app의 테스트 스크립트를 실행하여 테스팅을 진행할 수 있습니다. 아래 명령어를 실행하면, 모든 테스트 케이스의 테스트 결과가 커맨드 라인에 출력됩니다.
테스팅을 진행할 수 → 테스팅할 수 / 테스트를 진행할 수

2020-04-13 14:26 UTC, yeseulo commented on manuscript/react-maintenance/testing.md
> +다행히도 create-react-app에는 Jest가 미리 설치되어 있기 때문에, 커맨드 라인에서 create-react-app의 테스트 스크립트를 실행하여 테스팅을 진행할 수 있습니다. 아래 명령어를 실행하면, 모든 테스트 케이스의 테스트 결과가 커맨드 라인에 출력됩니다.
모든 테스트 케이스의 테스트 결과가 → 모든 테스트 케이스의 결과가 : 테스트 단어가 중복이라 하나 생략해도 되겠습니다.

2020-04-13 14:29 UTC, yeseulo commented on manuscript/react-maintenance/testing.md
> +"it" 블록은 한 개의 테스트 케이스를 나타냅니다. "it"문을 쓸 때는 테스트 성공 혹은 실패를 나타낼 설명을 함께 작성해주어야 합니다. 한 컴포넌트에 대한 테스트 케이스가 여러 개 있다면, "describe" 블록을 사용하여 이 케이스들을 하나의 테스트 스위트로 엮을 수 있습니다. 이 두 가지 블록들은 테스트 케이스를 정리하고, 가독성을 높이기 위해
작성해주어야 합니다. → 작성해야 합니다

2020-04-13 14:31 UTC, yeseulo commented on manuscript/react-maintenance/testing.md
> +방금 설치한 유틸리티 라이브러리와 함께 *src/App.test.js* 파일에 컴포넌트를 import해 줍니다.
import해 줍니다 → 가져옵니다.

2020-04-13 14:34 UTC, yeseulo commented on manuscript/react-maintenance/testing.md
> +이 테스트에서는 InputWithLabel 컴포넌트가 SearchForm 컴포넌트에서 올바른 prop을 전달받는지를 확인합니다. 다르게 말한다면, 이 테스트는 InputWithLabel 컴포넌트의 인터페이스(props)만 테스트하기 때문에 테스트가 InputWithLabel 컴포넌트가 렌더링되기 전에 끝난다는 뜻입니다. 그럼에도 불구하고 인터페이스를 그대
이미 모든 컴포넌트들이 렌더링되어 → 이미 모든 컴포넌트가 렌더링 되어

2020-04-14 14:10 UTC, haesookim commented on manuscript/react-maintenance/testing.md
> +  * 유닛 테스트, 통합 테스트, 스냅샷 테스트에 더 알아보기 위해 [Jest](https://jestjs.io/) 와 [Jest for React](https://www.robinwieruch.de/react-testing-jest/)를 활용할 수 있습니다.
앞에서 Jest를 모두 번역하지 않아서 그대로 두었는데, 그럼 '리액트를 위한 Jest'라고 번역해야 할까요? 섞여 있는 게 더 어색할 수도 있을 것 같아서요ㅠㅠ

2020-04-15 20:56 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +  * 유닛 테스트, 통합 테스트, 스냅샷 테스트에 더 알아보기 위해 [Jest](https://jestjs.io/) 와 [Jest for React](https://www.robinwieruch.de/react-testing-jest/)를 활용할 수 있습니다.
[[저자 블로그] 리액트를 위한 Jest 사용 방법] 어떨까요?
전에도 저는 저자 분이 자기 블로그를 추천할 때 마다 [저자 블로그]로 태그를 달았습니다.

2020-04-15 21:00 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +컴포넌트를 테스팅하려면 먼저 *src/App.js* 파일에서 작성한 컴포넌트들을 export해주어야 합니다.
다른 곳에 내보내야 합니다. 라고 되어 있어서 이렇게 수정해주세요.

2020-04-15 21:01 UTC, sujinleeme commented on manuscript/react-maintenance/testing.md
> +이미 [테스팅 라이브러리들](https://www.robinwieruch.de/react-testing-tutorial)이 많이 존재하기 때문에, 리액트 초심자들은 사용할 라이브러리를 고르는 데 어려움을 겪을 수도 있습니다. 우리는 이 튜토리얼에서 너무 강한 의견을 피력하는 것을 피하기 위해, 페이스북에서 개발한 [Jest](https://jestjs.i
우리는 이 튜토리얼에서 너무 강한 의견을 피력하는 것을 피하기 위해, -> 이 문장을 좀더 정돈해주시겠어요?

2020-04-16 10:05 UTC, haesookim commented on manuscript/react-maintenance/testing.md
> +  * 유닛 테스트, 통합 테스트, 스냅샷 테스트에 더 알아보기 위해 [Jest](https://jestjs.io/) 와 [Jest for React](https://www.robinwieruch.de/react-testing-jest/)를 활용할 수 있습니다.
네 알겠습니다. 그렇게 수정할게요!

2020-04-25 12:34 UTC, sujinleeme approved these changes

2020-04-25 12:35 UTC, merged