v2-react-modern-advanced-state
the-road-to-learn-react/the-road-to-react-korean pull request #16
Opened 2020-04-11 15:07 UTC by aeriChoi

react-modern
- advanced-state.md 초안

2020-04-12 05:39 UTC, sujinleeme requested changes

2020-04-12 05:39 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +어플리케이션의 모든 상태 관리는 리액트의 useState 훅을 많이 사용합니다. 보다 정교한 상태 관리는 리액트의 **useReducer** 훅을 통해 이루어집니다. 자바스크립트의 리듀서 개념은 커뮤니티를 반으로 나누기에 여기서는 다루지 않습니다. 하지만 글의 끝에서 제공되는 연습문제는 당신에게 많은 연습이 될 것입니다.
자바스크립트의 리듀서(reducer) 개념에 대해서는 많은 의논이 있기 때문에 여기서는 다루지 않습니다. 이번 절의 마지막에 있는 연습 문제가 많은 도움이 될 것입니다.

2020-04-12 05:39 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +리듀서의 `action`은 `타입`과 관련 있습니다. 리듀서의 조건과 타입이 일치할 경우 동작이 수행되며 조건이 일치하지 않을 경우 오류를 반환합니다. `storiesReducer`는 하나의 `타입을 포함한 후 현재 상태를 사용하여 새 상태를 계산하지 않고 들어오는 action의` 데이터를 전달합니다. `새로운 상태는 단순히` 전달된 데이터에 불과합니다.
타입(type)으로 수정해주세요,

2020-04-12 05:39 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +앱 컴포넌트 안에서 `stories`를 관리하려면 `useState`를 `useReducer`로 교환하십시오. 새로운 훅은 리듀서의 초기 상태를 인자로 받고 두 요소가 있는 배열을 반환합니다. 첫 요소는 현재 상태이며, 두 번째 요소는 상태를 업데이트하는 함수입니다. (디스패치 함수라고도 합니다.)
교환하십시오 -> 교환합니다.

2020-04-12 05:39 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +앱 컴포넌트 안에서 `stories`를 관리하려면 `useState`를 `useReducer`로 교환하십시오. 새로운 훅은 리듀서의 초기 상태를 인자로 받고 두 요소가 있는 배열을 반환합니다. 첫 요소는 현재 상태이며, 두 번째 요소는 상태를 업데이트하는 함수입니다. (디스패치 함수라고도 합니다.)
디스패치 함수(dispatch function) 영문으로 해주시고 * 를 추가해주세요. (마크다운 확인)

2020-04-12 05:39 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +이제 리듀서는 새로운 조건부의 상태 변경 사례를 처리해야합니다. 스토리를 삭제하는 조건이 충족 되면 리듀서는 스토리를 제거하기 위해 필요한 모든 구현 세부사항을 가지게 됩니다. 이는 현재 상태에서 스토리를 제거하고 필터링 된 스토리의 새 목록을 상태로 리턴하는 데 필요한 모든 정보 (항목 ID)를 제공합니다.
문장이 이상합니다. 다시 고쳐주세요.

2020-04-12 05:39 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +자바스크립트에서 리듀서 개념과 리액트의 useReducer 훅 사용법을 완전히 이해하려면 연습 링크를 확인하십시오.
확인하십시오 -> 확인하세요 로 수정하세요.

2020-04-12 05:40 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +### 실습하기:
:를 삭제해주세요.

2020-04-12 13:27 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +* [마지막 장의 소스 코드를 확인하세요](https://codesandbox.io/s/github/the-road-to-learn-react/hacker-stories/tree/hs/React-Advanced-State).
[마지막 장의 소스 코드](링크)를 확인하세요.
링크 위치를 수정해주세요.

2020-04-12 13:28 UTC, sujinleeme requested changes

2020-04-12 13:28 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +  * [마지막 장의 변경 사항을 확인하세요](https://github.com/the-road-to-learn-react/hacker-stories/compare/hs/React-Conditional-Rendering...hs/React-Advanced-State?expand=1).
[마지막 장의 변경 사항] (링크)를 확인하세요.
링크 위치를 수정해주세요.

2020-04-12 13:35 UTC, aeriChoi commented on manuscript/react-modern/advanced-state.md
> +* [마지막 장의 소스 코드를 확인하세요](https://codesandbox.io/s/github/the-road-to-learn-react/hacker-stories/tree/hs/React-Advanced-State).
링크 위치를 확인하라는게 무슨 말씀이신가요~?

2020-04-12 13:35 UTC, aeriChoi commented on manuscript/react-modern/advanced-state.md
> +  * [마지막 장의 변경 사항을 확인하세요](https://github.com/the-road-to-learn-react/hacker-stories/compare/hs/React-Conditional-Rendering...hs/React-Advanced-State?expand=1).
링크 위치를 확인하라는게 무슨 말씀이신가요~?

2020-04-12 23:40 UTC, sujinleeme commented on manuscript/react-modern/advanced-state.md
> +  * [마지막 장의 변경 사항을 확인하세요](https://github.com/the-road-to-learn-react/hacker-stories/compare/hs/React-Conditional-Rendering...hs/React-Advanced-State?expand=1).
```
* [마지막 장의 소스 코드를 확인하세요](https://codesandbox.io/s/github/the-road-to-learn-react/hacker-stories/tree/hs/React-Advanced-State).
```
를


```
* [마지막 장의 소스 코드](https://codesandbox.io/s/github/the-road-to-learn-react/hacker-stories/tree/hs/React-Advanced-State)를 확인하세요. 
```
로 수정해주세요.

2020-04-13 04:13 UTC, aeriChoi commented on manuscript/react-modern/advanced-state.md
> +  * [마지막 장의 변경 사항을 확인하세요](https://github.com/the-road-to-learn-react/hacker-stories/compare/hs/React-Conditional-Rendering...hs/React-Advanced-State?expand=1).
넵 알겠습니다~!

2020-04-13 09:35 UTC, merged