v2-reusable-components/initial commit
the-road-to-learn-react/the-road-to-react-korean pull request #18
Opened 2020-04-12 12:28 UTC by yein9

prop을 프로퍼티로 변경을 해야하나 고민했지만 원문그대로 prop으로 사용했습니다.
그리고 읽어보기 란의 다음장 관련 링크를 어디로 연결하면 좋을까요?? 피드백 주시면 감사하겠습니다.

2020-04-12 13:23 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +* [재사용이 가능한 컴포넌트]()에 대해 더 읽어보기
링크가 빠져있습니다.

2020-04-12 13:25 UTC, sujinleeme requested changes

2020-04-12 13:25 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> + * [지난 장과 달라진 점](https://github.com/the-road-to-learn-react/hacker-stories/compare/hs/React-Fragments...hs/Reusable-React-Component?expand=1) 확인하기
확인하세요.로 마쳐주세요.

2020-04-12 13:25 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +### 읽어보기:
:를 삭제해주세요.

2020-04-12 13:25 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +App 컴포넌트의 `type`  prop은 InputWithLabel 컴포넌트로 전달되지 않기 때문에 외부에서 명시되지 않아도 됩니다. 함수 서명의 [기본 매개변수](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)가 입력 필드를 대신
함수 시그니처의 기본 파라미터로 수정해주세요.

2020-04-12 13:25 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +## 재사용이 가능한 리액트 컴포넌트
리액트 컴포넌트 재사용이 어떨까요?

2020-04-12 13:25 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +Search 컴포넌트를 좀 더 자세히 살펴봅시다. 라벨의 엘리먼트에는 "Search:"라는 텍스트가 있습니다. id/htmlFor 속성에는`search `라는 값을 갖는` search`식별자가 있습니다. 그리고  `onSearch`라는 콜백 함수도 있습니다. 이 컴포넌트들은 `search`와 밀접하게 관련되어 있어 다른 애플리케이션과 `search`를 하
id/htmlFor 순서가 뒤바뀐 듯 합니다.

2020-04-12 13:25 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +* [재사용이 가능한 컴포넌트]()에 대해 더 읽어보기
읽어보세요로 수정해주세요.

2020-04-13 10:32 UTC, ejolie commented on manuscript/react-modern/reusable-components.md
> +몇 개의 수정으로 Search 컴포넌트를 재사용성이 높은 컴포넌트로 만들었습니다.  내부 구현의 세부사항을 이름을 일반화했고, 새로운 컴포넌트에게 외부에서 필요한 모든 정보를 제공하는 큰 API를 주었습니다.
- 몇 개의 수정으로 -> 몇몇 부분을 수정하여 / 몇 가지 변화로 / 몇몇 변경사항을 통해 
  등으로 고치면 더욱 자연스러울 것 같습니다.

- 내부 구현의 세부사항**을** 이름**을** -> "을"이 반복되는 것을 고치면 좋을 것 같습니다.

2020-04-13 14:09 UTC, yeseulo commented on manuscript/react-modern/reusable-components.md
> +Search 컴포넌트를 좀 더 자세히 살펴봅시다. 라벨의 엘리먼트에는 "Search:"라는 텍스트가 있습니다. id/htmlFor 속성에는`search `라는 값을 갖는` search`식별자가 있습니다. 그리고  `onSearch`라는 콜백 함수도 있습니다. 이 컴포넌트들은 `search`와 밀접하게 관련되어 있어 다른 애플리케이션과 `search`를 하
`` 앞뒤로 띄어쓰기 공백 수정이 필요합니다.

2020-04-13 14:11 UTC, yeseulo commented on manuscript/react-modern/reusable-components.md
> +Search 컴포넌트가 실질적으로 "검색"기능을 갖고 있지 않기 때문에, search 도메인 속성들을 다른 애플리케이션에서도 재사용이 가능하도록 하는 것이 어렵지 않습니다. 추가적인 `id`와 `label` prop을 Search 컴포넌트로 넘겨줍니다. 그리고 실제 값과 콜백 함수 핸들러의 이름을 조금 더 추상적인 이름으로 바꾸고 컴포넌트의 이름도 함께
"검색"기능을 갖고 있지 않기 때문에 → "검색" 기능이 있지 않기 때문에

2020-04-13 14:13 UTC, yeseulo commented on manuscript/react-modern/reusable-components.md
> +아직 완전하게 재사용이 가능하진 않습니다. 만약 숫자(`number`)나 전화번호(`tel`) 같은 데이터에 대한 입력 필드를 원하면, 외부에서도 입력 필드의 `type`속성에 접근할 수 있도록 해야 합니다.
`type`속성에 → `type` 속성에: 띄어쓰기 해주세요

2020-04-13 14:15 UTC, yeseulo commented on manuscript/react-modern/reusable-components.md
> +App 컴포넌트의 `type`  prop은 InputWithLabel 컴포넌트로 전달되지 않기 때문에 외부에서 명시되지 않아도 됩니다. 함수 서명의 [기본 매개변수](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)가 입력 필드를 대신
명시되지 않아도 된다 보다는 명시되지 않는다, 지정되지 않는다 면 어떨까요

2020-04-13 14:17 UTC, yeseulo commented on manuscript/react-modern/reusable-components.md
> +몇 개의 수정으로 Search 컴포넌트를 재사용성이 높은 컴포넌트로 만들었습니다.  내부 구현의 세부사항을 이름을 일반화했고, 새로운 컴포넌트에게 외부에서 필요한 모든 정보를 제공하는 큰 API를 주었습니다.
'내부 구현의...' 앞에 스페이스가 하나 더 들어갔습니다.

2020-04-24 21:47 UTC, yein9 commented
모두 수정했습니다. 너무 늦어 죄송합니다ㅠㅠㅠ

2020-04-24 22:10 UTC, sujinleeme requested changes

2020-04-24 22:10 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +몇몇 변경사항을 통해 Search 컴포넌트를 재사용성이 높은 컴포넌트로 만들었습니다. 내부 구현의 세부사항의 이름을 일반화했고, 새로운 컴포넌트에게 외부에서 필요한 모든 정보를 제공하는 큰 API를 주었습니다.
이 문장이 잘 이해가 안가서 수정 부탁드립니다.

2020-04-24 22:12 UTC, sujinleeme requested changes

2020-04-24 22:12 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +App 컴포넌트의 `type` prop은 InputWithLabel 컴포넌트로 전달되지 않기 때문에 외부에서 명시되지 않습니다. 함수 시그니처의 [기본 파라미터](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)가 입력 필드를 대신합니
외부에서 명시되지 않습니다.  무슨 뜻인지 모르겠어요.

2020-04-24 22:12 UTC, sujinleeme commented on manuscript/react-modern/reusable-components.md
> +Search 컴포넌트를 좀 더 자세히 살펴봅시다. 라벨의 엘리먼트에는 "Search:"라는 텍스트가 있습니다. id/htmlFor 속성에는 `search`라는 값을 갖는 `search`식별자가 있습니다. 그리고 `onSearch`라는 콜백 함수도 있습니다. 이 컴포넌트들은 `search`와 밀접하게 관련되어 있어 다른 애플리케이션과 `search`를 하지
이 컴포넌트들은 `search`와 밀접하게 관련되어 있어 다른 애플리케이션과 `search`를 하지 않는 작업에서는 재사용이 어렵습니다. 
-> 이 컴포넌트들은 `search`와 밀접하게 관련되어 있어, 다른 애플리케이션에서 `search`를 사용하지 않는다면 재사용이 어렵습니다. 가 어떨까요.

2020-05-03 14:49 UTC, yein9 commented on manuscript/react-modern/reusable-components.md
> +Search 컴포넌트를 좀 더 자세히 살펴봅시다. 라벨의 엘리먼트에는 "Search:"라는 텍스트가 있습니다. id/htmlFor 속성에는 `search`라는 값을 갖는 `search`식별자가 있습니다. 그리고 `onSearch`라는 콜백 함수도 있습니다. 이 컴포넌트들은 `search`와 밀접하게 관련되어 있어 다른 애플리케이션과 `search`를 하지
그렇게 수정했습니다!

2020-05-03 14:50 UTC, yein9 commented
모두 수정했습니다.

2020-05-07 11:40 UTC, merged