Translate react modern/props
the-road-to-learn-react/the-road-to-react-korean pull request #22
Opened 2020-04-12 20:39 UTC by constmoon

2020-04-12 20:41 UTC, constmoon commented on manuscript/react-modern/props.md
> +이 작업을 통해 list/stories 변수가 App 컴포넌트의 전역 스코프를 오염시키는 것을 방지했습니다. `stories` 는 App 컴포넌트에서 직접 사용되지는 않지만, App의 자식 컴포넌트인 List 컴포넌트에서는 사용되기 때문에 props로 전달했습니다. 이제 첫번째 함수 시그니쳐의 인수인 `props` 를 통해 stories에 접근할 수 있게
`스코프 오염(변수로 설정한 값이 다른 값으로 대체되거나 하는 것)을 방지했습니다` 와 같은 부연 설명이 필요할까요?

2020-04-12 23:44 UTC, sujinleeme requested changes

2020-04-12 23:44 UTC, sujinleeme commented on manuscript/react-modern/props.md
> +우리는 현재 `list` 변수를 어플리케이션의 전역 변수로 사용하고 있습니다. 변수를 App 컴포넌트의 전역 스코프(scope: 유효범위)에서 직접 사용하고, List 컴포넌트에서도 똑같이 사용했습니다. 이는 변수를 1개만 사용한다면 문제가 되지 않지만, 여러 개의 변수를 여러 컴포넌트에서 사용할 때는 효율적이지 못한 방법입니다.
`scope: 유효범위` 없어도 될 것 같아요.

2020-04-12 23:44 UTC, sujinleeme commented on manuscript/react-modern/props.md
> +App 컴포넌트에 변수 `stories`를 생성하고, 이 이름으로 List 컴포넌트에 전달하겠습니다. 그러나 이 props는 List 컴포넌트가 인스턴스화 될 때 `list` 속성으로 할당됩니다. List 컴포넌트의 함수 시그니처(function signature: 함수의 원형에 명시되는 매개변수 리스트)를 통해 `props ` 객체는 `list`으로 접
function signature: 함수의 원형에 명시되는 매개변수 리스트를 블로그에서 찾으신 것 같은데 가급적이면 MDN을 참고해서 주석을 달아주세요.

https://developer.mozilla.org/en-US/docs/Glossary/Signature/Function

2020-04-12 23:44 UTC, sujinleeme commented on manuscript/react-modern/props.md
> +이 작업을 통해 list/stories 변수가 App 컴포넌트의 전역 스코프를 오염시키는 것을 방지했습니다. `stories` 는 App 컴포넌트에서 직접 사용되지는 않지만, App의 자식 컴포넌트인 List 컴포넌트에서는 사용되기 때문에 props로 전달했습니다. 이제 첫번째 함수 시그니쳐의 인수인 `props` 를 통해 stories에 접근할 수 있게
스코프 오염은 영어적인 표현이라 변수로 설정한 값이 다른 값으로 대체되거나 하는 것이 좋을 것 같아요.

2020-04-13 09:40 UTC, constmoon commented on manuscript/react-modern/props.md
> +App 컴포넌트에 변수 `stories`를 생성하고, 이 이름으로 List 컴포넌트에 전달하겠습니다. 그러나 이 props는 List 컴포넌트가 인스턴스화 될 때 `list` 속성으로 할당됩니다. List 컴포넌트의 함수 시그니처(function signature: 함수의 원형에 명시되는 매개변수 리스트)를 통해 `props ` 객체는 `list`으로 접
v1 버전을 참고해서 작성했는데 수정하겠습니다! 링크 공유 감사해요.

2020-04-13 14:02 UTC, yeseulo commented on manuscript/react-modern/props.md
> +우리는 현재 `list` 변수를 어플리케이션의 전역 변수로 사용하고 있습니다. 변수를 App 컴포넌트의 전역 스코프(scope: 유효범위)에서 직접 사용하고, List 컴포넌트에서도 똑같이 사용했습니다. 이는 변수를 1개만 사용한다면 문제가 되지 않지만, 여러 개의 변수를 여러 컴포넌트에서 사용할 때는 효율적이지 못한 방법입니다.
1개 -> 한 개 로 쓰는 것이 좋겠습니다.

2020-04-13 14:06 UTC, yeseulo commented on manuscript/react-modern/props.md
> +Props를 사용하면 변수에 저장된 데이터를 한 컴포넌트에서 다른 컴포넌트로 전달할 수 있습니다. Props를 사용하기 전에는 전역 스코프에 선언한 list를 App 컴포넌트 안에서 호출하고, 필요한 기능에 맞게 이름을 바꿔서 사용했었습니다.
원문은 we'll move~, and rename~ 라서 과거형으로 표현하신 부분을 현재 시제로 쓰면 어떨까요?

2020-04-14 06:29 UTC, constmoon commented on manuscript/react-modern/props.md
> +Props를 사용하면 변수에 저장된 데이터를 한 컴포넌트에서 다른 컴포넌트로 전달할 수 있습니다. Props를 사용하기 전에는 전역 스코프에 선언한 list를 App 컴포넌트 안에서 호출하고, 필요한 기능에 맞게 이름을 바꿔서 사용했었습니다.
지적 감사합니다. 이 장에서 props를 설명하기 전에 move&rename을 하겠다는 의미인데, 제가 문장을 잘못 이해한 것 같아요. 수정하겠습니다!

2020-04-14 06:31 UTC, constmoon commented
리뷰 반영해서 수정했습니다.

2020-04-15 13:18 UTC, merged