[v2] react modern/conditional rendering
the-road-to-learn-react/the-road-to-react-korean pull request #24
Opened 2020-04-12 20:52 UTC by constmoon

2020-04-12 23:25 UTC, sujinleeme requested changes

2020-04-12 23:25 UTC, sujinleeme commented on manuscript/react-modern/conditional-rendering.md
> +리액트에서 비동기 데이터를 처리하다보면, 데이터가 있기도 하고 데이터가 없기도 하는 '조건부 상태'가 생깁니다. 이미 앞에서 다룬 내용이기도 합니다. 초기 상태가 `null`이 아니라 빈 리스트이기 때문입니다. 만약 null이었다면 이 문제는 JSX에서 다뤄야하겠지요. 그러나 `[]` 이기 때문에, 만약 검색을 위해 빈 배열에  `filter()` 를 사
`filter()`  앞뒤로 빈공백을 삭제해주세요. 
띄워쓰기와 맞춤법 검사 한번 더 부탁드립니다.

2020-04-12 23:25 UTC, sujinleeme commented on manuscript/react-modern/conditional-rendering.md
> +조건부 렌더링에 문제가 생긴 경우, 사용자에게 피드백을 제공해야 합니다. 이번에는 뭔가를 렌더링하거나 아무것도 렌더링하지 않도록 해봅니다. 한쪽이 `null`을 반환하는 삼항 조건 연산자를 대신에 논리 연산자인 `&&` 를 사용합니다.
`&&`  뒤에 공백 삭제해주세요.

2020-04-12 23:26 UTC, sujinleeme commented on manuscript/react-modern/conditional-rendering.md
> +자바스크립트에서는 `true && 'Hello World'` 는 항상 'Hello World'으로 간주됩니다. 마찬가지로 `false && 'Hello World'` 의 경우 항상 거짓으로 간주됩니다. 리액트에서는 이러한 특성을 장점으로 사용할 수 있습니다. 조건이 참이면, `&&` 논리 연산자 뒷부분 내용이 출력됩니다. 조건이 거짓이면 리액트는 표현식을
역시 `뒤 은는이가 가 오면 빈공백을 삭제해주세요.

2020-04-12 23:26 UTC, sujinleeme requested changes
띄워쓰기 체크 부탁드립니다.

2020-04-13 13:41 UTC, yeseulo commented on manuscript/react-modern/conditional-rendering.md
> +리액트에서 비동기 데이터를 처리하다보면, 데이터가 있기도 하고 데이터가 없기도 하는 '조건부 상태'가 생깁니다. 이미 앞에서 다룬 내용이기도 합니다. 초기 상태가 `null`이 아니라 빈 리스트이기 때문입니다. 만약 null이었다면 이 문제는 JSX에서 다뤄야하겠지요. 그러나 `[]` 이기 때문에, 만약 검색을 위해 빈 배열에  `filter()` 를 사
- 처리하다보면 → 처리하다 보면
- 다뤄야하겠지요 → 다뤄야 하겠지요

2020-04-13 13:42 UTC, yeseulo commented on manuscript/react-modern/conditional-rendering.md
> +비동기 데이터는 오류도 처리를 해야합니다. 현재 시뮬레이션 환경에서는 오류가 발생하지 않더라도, 다른 API에서 데이터를 가져오기 시작하면 오류가 발생할 수 있습니다. 오류를 저장하는 상태를 만들고, promise의 `catch()` 블록에서 처리하도록 합니다.
처리를 해야합니다 → 처리를 해야 합니다

2020-04-13 13:44 UTC, yeseulo commented on manuscript/react-modern/conditional-rendering.md
> +조건부 렌더링에 문제가 생긴 경우, 사용자에게 피드백을 제공해야 합니다. 이번에는 뭔가를 렌더링하거나 아무것도 렌더링하지 않도록 해봅니다. 한쪽이 `null`을 반환하는 삼항 조건 연산자를 대신에 논리 연산자인 `&&` 를 사용합니다.
삼항 조건 연산자를 대신에 → 삼항 조건 연산자 대신에: '를' 을 빼는 것이 '대신에' 와 자연스러운 것 같아요

2020-04-13 13:45 UTC, yeseulo commented on manuscript/react-modern/conditional-rendering.md
> +자바스크립트에서는 `true && 'Hello World'` 는 항상 'Hello World'으로 간주됩니다. 마찬가지로 `false && 'Hello World'` 의 경우 항상 거짓으로 간주됩니다. 리액트에서는 이러한 특성을 장점으로 사용할 수 있습니다. 조건이 참이면, `&&` 논리 연산자 뒷부분 내용이 출력됩니다. 조건이 거짓이면 리액트는 표현식을
간주됩니다  →  간주합니다 가 어떨까요?

2020-04-13 13:47 UTC, yeseulo commented on manuscript/react-modern/conditional-rendering.md
> +### 읽어보기
Exercises는 모두 '실습하기'로 써서 맞추면 좋겠습니다.

2020-04-14 14:06 UTC, constmoon commented
리뷰 감사합니다. 반영하여 수정했습니다.

2020-04-15 13:49 UTC, sujinleeme requested changes

2020-04-15 13:49 UTC, sujinleeme commented on manuscript/react-modern/conditional-rendering.md
>  * [지난 장에서 사용한 코드](https://codesandbox.io/s/github/the-road-to-learn-react/hacker-stories/tree/hs/React-Conditional-Rendering)를 확인하세요.
동일한 코드인데 코드샌드박스와 깃허브 버전으로 나뉜거죠? 

'[코드샌드박스] 지난 장에서 수정된 코드' 
'[깃허브] 지난 장에서 수정된 코드' 라고 앞에 달아주실 수 있을까요?

2020-04-17 07:44 UTC, constmoon commented on manuscript/react-modern/conditional-rendering.md
>  * [지난 장에서 사용한 코드](https://codesandbox.io/s/github/the-road-to-learn-react/hacker-stories/tree/hs/React-Conditional-Rendering)를 확인하세요.
네 깃허브는 diff를 보여주는 용도로 링크된 거 같아요. 수정했습니다!

2020-04-17 15:34 UTC, merged