[v2] react modern/data fetching
the-road-to-learn-react/the-road-to-react-korean pull request #25
Opened 2020-04-12 21:22 UTC by constmoon

2020-04-12 23:23 UTC, sujinleeme requested changes
띄워쓰기 한번만 체크 부탁드릴게요.

2020-04-12 23:23 UTC, sujinleeme commented on manuscript/react-modern/data-fetching.md
> +우리는 현재 데이터를 가져오고는 있지만, 우리가 스스로 설정한 의사(pseudo) 데이터일 뿐입니다. 이번 장에서는 외부 API에서 데이터를 가져올 때 필요한 비동기 리액트 및 고급 상태 관리에 대해 알아봅니다. 믿을만하고 유익한 [Hacker News API](https://hn.algolia.com/api)를 사용하여 인기 있는 기술 관련 기사들을 가
현재 데이터는 실제 사용하는 데이터가 아니라 임시 데이터입니다. 로 수정해주세요.

Hacker News API를 해커 뉴스 API로 수정해주세요.

2020-04-12 23:23 UTC, sujinleeme commented on manuscript/react-modern/data-fetching.md
> +먼저, `API_ENDPOINT` (A)는 특정 쿼리(검색 주제)에 대한 인기 있는 기술 관련 기사들을 가져오는 데에 사용됩니다. 이 경우 React (B)에 대한 기사를 가져옵니다. 둘째, 네이티브 브라우저의 [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)사용하여 요청을 보
Fetch API의 경우 응답을 JSON 으로 변환해야합니다 (C).  마지막으로 반환된 결괏값은 각각 다른 데이터 구조를 따르며 (D),  수정해주세요. 

React를 리액트로 수정해주세요.

맞춤법 검사기로 띄워쓰기를 다시 한번 확인해주세요.

2020-04-12 23:23 UTC, sujinleeme commented on manuscript/react-modern/data-fetching.md
> +이전 코드에서 우리는 [자바스크립트 템플릿 리터럴](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)로 문자 보간기능을 사용했습니다. 이 기능이 자바스크립트에 등장하기 전까지는 문자열에 + 연산자를 사용했었습니다.
사용했었습니다 -> 했습니다로 수정해주세요.

2020-04-12 23:23 UTC, sujinleeme commented on manuscript/react-modern/data-fetching.md
> +브라우저를 열어 Hacker News API에서 가져온 초기 쿼리와 관련된 기사를 확인하세요. 샘플 기사와 똑같은 데이터 구조를 사용했으므로 아무것도 변경할 필요가 없습니다. 또한 검색 기능으로 기사들을 가져온 후 필터링을 할 수도 있습니다. 다음 장에서 이런 것들을 변경해 볼 것입니다. App 컴포넌트의 경우, 데이터 가져오기를 구현하는 부분은 많지 않
Hacker News -> 해커 뉴스로 수정해주세요.
다음 장에서 이 기능을 구현해 볼 것입니다.

리액트에서 비동기 데이터를 상태로 관리하는 방법을 학습하는 데에는 필요한 부분입니다.
-> 리액트에서 비동기 데이터를 상태로 관리하는 방법에 필요한 개념을 모두 학습했습니다 로 수정해주세요.

2020-04-14 14:36 UTC, constmoon commented
리뷰 반영하여 수정했습니다. 감사합니다.

2020-04-15 13:15 UTC, merged