Update intro.md
the-road-to-learn-react/the-road-to-react-korean pull request #36
Opened 2020-04-19 15:21 UTC by YeSeulBae

작가 소개 중반까지 해석,
4/20(월) 자정까지 추가 업데이트 예정입니다.

2020-04-24 22:15 UTC, sujinleeme commented on intro.md
> +몇년 간, 로빈은 Small Improvements라는 회사에서 뛰어난 팀의 엔지니어들과 큰 규모의 애플리케이션들을 개발했습니다. 이 회사는 고객들이 회사들에게 피드백을 줄 수 있는 Saas 제품을 만들었습니다. 이 애플리케이션은 자바스크립트로 프론트엔드, 자바로 백엔드 개발이 되었습니다.
이전 버전에서 번역한 내용에 저자 소개가 거의 비슷합니다. 참고하세요~

2020-04-24 22:15 UTC, sujinleeme commented on intro.md
> +## 작가 소개
저자 로 변경해주세요.

2020-04-27 07:19 UTC, yeseulo commented on intro.md
> +'리액트 도움닫기'는 리액트의 기초를 배울 수 있습니다. 여러분은 복잡한 도구없이 순수한 리액트만으로 훌륭한 애플리케이션을 만들 수 있습니다. 리액트 설치부터 기초, 서버 배포까지, 리액트 개발 전 과정을 설명합니다. 각 장마다 추가 읽기 자료 및 실습 자료를 제시했습니다. 이 책을 읽고난 후, 리액트로 여러분의 애플리케이션을 직접 만들 수 있습니다. 이
```diff
- 도구없이
+ 도구 없이
```
```diff
- 각 장마다
+ 각 장에 (또는 장마다)
```
```diff
- 읽고난 후
+ 읽고 난 후
```

2020-05-16 08:53 UTC, sujinleeme commented on intro.md
> -**How to get updates?**
번역이 모두 안되어 있습니다. 한달 넘게 진행이 안되고 있는데 확인부탁드려요.

2020-05-21 16:28 UTC, sujinleeme commented on intro.md
> +'리액트 도움닫기'는 리액트의 기초를 배울 수 있습니다. 여러분은 복잡한 도구 없이 순수한 리액트만으로 훌륭한 애플리케이션을 만들 수 있습니다. 리액트 설치부터 기초, 서버 배포까지, 리액트 개발 전 과정을 설명합니다. 각  장에 추가 읽기 자료 및 실습 자료를 제시했습니다. 이 책을 읽고 난 후, 리액트로 여러분의 애플리케이션을 직접 만들 수 있습니다.
리액트 도움닫기 아니고 더 로드 투 리액트로 수정해주세요.

2020-05-21 16:28 UTC, sujinleeme commented on intro.md
> +리액트 도움닫기에서는, 여러분이 더 넓은 리액트 생태계로 뛰어들 수 있도록 기초를 제공합니다. 외부 상태 관리 라이브러리와 도구보다는 리액트에 대한 정보를 다룰 것입니다. 그것은 실제 리액트 애플리케이션의 전반적인 개념과 패턴, 모범 예제를 설명합니다.
리액트 도움닫기 -> 더 로드 투 리액트

2020-05-21 16:29 UTC, sujinleeme commented on intro.md
> -If you have bought the book on Amazon, you may have seen that the book is available on my website too. Since I use Amazon as one way to monetize my often free content, I honestly thank you for your s
번역 내용이 본문과 일치하지 않습니다.

2020-05-21 16:34 UTC, sujinleeme requested changes
번역 투 고쳐주시고, 맞춤법 검사기로 본문 확인부탁드립니다.

2020-05-21 16:34 UTC, sujinleeme commented on intro.md
> +몇년 간, 로빈은 Small Improvements라는 회사에서 뛰어난 팀의 엔지니어들과 큰 규모의 애플리케이션들을 개발했습니다. 이 회사는 고객들이 회사들에게 피드백을 줄 수 있는 Saas 제품을 만들었습니다. 이 애플리케이션은 자바스크립트로 프론트엔드, 자바로 백엔드 개발이 되었습니다. Small Improvements의 Frontend 초창기 제품은
이 부분은 제가 전에 번역한 내용을 참고하셔서 수정해주세요.
https://github.com/the-road-to-learn-react/the-road-to-learn-react-korean/blob/master/manuscript/foreword.md#%EC%A7%80%EC%9D%80%EC%9D%B4-%EB%A1%9C%EB%B9%88-%EC%9C%84%EC%96%B4%ED%81%ACrobin-wieruch

2020-05-21 16:34 UTC, sujinleeme commented on intro.md
> -Also, if you have purchased a print book, make sure to take notes in the book. It was my intention to keep the printed book extra large, for the sake of giving larger code snippets enough space, but
제대로 번역이 되어 있지 않습니다. 수정 부탁드려요!

2020-05-21 17:48 UTC, yyhan0915 commented on intro.md
> +몇년 간, 로빈은 Small Improvements라는 회사에서 뛰어난 팀의 엔지니어들과 큰 규모의 애플리케이션들을 개발했습니다. 이 회사는 고객들이 회사들에게 피드백을 줄 수 있는 Saas 제품을 만들었습니다. 이 애플리케이션은 자바스크립트로 프론트엔드, 자바로 백엔드 개발이 되었습니다.
안녕하세요. 다름이 아니라 저자명의 번역에 대해서 문의 드립니다. Robin wieruch를 한글로 음성번역 하면 '로빈 비루흐'가 되지 않을까요?

2020-05-21 19:01 UTC, yyhan0915 commented on intro.md
> +'리액트 도움닫기'는 리액트의 기초를 배울 수 있습니다. 여러분은 복잡한 도구 없이 순수한 리액트만으로 훌륭한 애플리케이션을 만들 수 있습니다. 리액트 설치부터 기초, 서버 배포까지, 리액트 개발 전 과정을 설명합니다. 각  장에 추가 읽기 자료 및 실습 자료를 제시했습니다. 이 책을 읽고 난 후, 리액트로 여러분의 애플리케이션을 직접 만들 수 있습니다.
'로드 투 리액트'에서는 리액트의 기초를 가르치고 있습니다. 복잡한 도구를 배제한 체 여러분은 리액트만으로도 현업 수준의 어플리케이션을 만들어 내게 될 것 입니다. 이 책은 프로젝트 설치에서 부터 서버에 배포하기 까지, 모든 과정이 담겨 있습니다. 각 장 마다 참조할 만한 읽기 자료 및 예제들을 실었습니다. 본서를 완독하게 된 뒤, 독자 여러분 께서는 자신 만의 어플리케이션을 리액트로 개발할 수 있게 되리라 생각 합니다. 또한 책의 내용들은 저자인 본인과 관련 커뮤티니에서 최신 정보를 담아낼 수 있도록 업데이트 되고 있습니다.

2020-05-24 09:18 UTC, sujinleeme commented on intro.md
> +* jQuery를 하는 JavaScript에 숙련된 사람 : jQuery, MooTools, Dojo를 사용하는 JavaScript를 집중적으로 사용했었다면, 새로운 JavaScript의 도래가 누군가에게는 이전과는 다르게 느껴질 수 있습니다. 그러나 JavaScript와 HTML을 기반으로 하는 기본 지식은 크게 바뀌지 않았으며, 이 책이 여러분들이 리
자바스크립트로 수정해주세요.

2020-05-24 09:19 UTC, sujinleeme commented on intro.md
> +* 다른 SPA 프레임워크를 사용했던 JavaScript 개발자 : Angular 혹은 Vue를 사용했었다면, 리액트를 사용하는 것과 많은 차이점이 있을 것입니다. 그러나 SPA 프레임워크 모두 JavaScript와 HTML과 동일한 기본 구조를 가지고 있습니다. 리액트를 편하게 생각하면, 금방 리액트 사용에 적응할 수 있습니다.
앵귤러 뷰로 수정해주세요. 자바스크립트로 고쳐주세요.

2020-05-24 09:20 UTC, sujinleeme requested changes
conflicts 해결 해주세요. 수정 부탁드립니다!

2020-05-24 09:20 UTC, sujinleeme commented on intro.md
> +'더 로드 투 리액트'에서는 리액트의 기초를 가르치고 있습니다. 여러분은 복잡한 도구 없이 순수한 리액트만으로 현업 수준의 애플리케이션을 만들 수 있습니다. 이 책은 리액트 설치부터 기초, 서버 배포까지, 리액트 개발 전 과정이 담겨 있습니다. 각 장마다 참조할 만한 읽기 자료 및 실습 예제들을 실었습니다. 이 책을 읽고 난 후, 리액트로 여러분의 애플리
'더 로드 투 리액트'에서는 리액트의 기초를 가르치고 있습니다. ->
'더 로드 투 리액트'에서는 리액트의 기초를 다룹니다.

2020-05-24 09:21 UTC, sujinleeme commented on intro.md
> +'더 로드 투 리액트'에서는 리액트의 기초를 가르치고 있습니다. 여러분은 복잡한 도구 없이 순수한 리액트만으로 현업 수준의 애플리케이션을 만들 수 있습니다. 이 책은 리액트 설치부터 기초, 서버 배포까지, 리액트 개발 전 과정이 담겨 있습니다. 각 장마다 참조할 만한 읽기 자료 및 실습 예제들을 실었습니다. 이 책을 읽고 난 후, 리액트로 여러분의 애플리
이 자료는 본인과 커뮤니티에 의해 최신으로 유지됩니다.
->본 저서는 저자와 커뮤니티가 함께 최신 버전으로 유지하고 있습니다.

2020-05-24 09:21 UTC, sujinleeme commented on intro.md
> +'더 로드 투 리액트'에서는, 여러분이 더 넓은 리액트 생태계로 뛰어들 수 있도록 기초를 제공합니다. 외부 상태 관리 라이브러리와 도구보다는 리액트에 대한 정보를 다룰 것입니다. 그것은 실제 리액트 애플리케이션의 전반적인 개념과 패턴, 모범 예제를 설명합니다.
그것은 실제 리액트 애플리케이션의 전반적인 개념과 패턴, 모범 예제를 설명합니다. 
->  실제 리액트 애플리케이션의 전반적인 개념과 패턴, 모범 예제를 설명합니다.

2020-05-24 09:22 UTC, sujinleeme commented on intro.md
> +본질적으로, 여러분은 쪽수 매기기, 클라이언트와 서버 측 검색 기능을 가진 스크래치 그리고 정렬과 같은 선진화된 상호작용으로부터 여러분의 리액트 애플리케이션을 만드는 법을 배울 수 있습니다. 저는 이 책이 리액트와 자바스크립트에 대한 나의 열정을 포착하길 바라며, 여러분이 시작하는 데 있어서 도움이 되길 바랍니다.
콤마가 전반적으로 너무 많습니다. 불필요한 콤마를 삭제해주세요.

2020-05-24 09:23 UTC, sujinleeme commented on intro.md
> +몇 년간, 로빈은 Small Improvements라는 회사에서 뛰어난 팀의 엔지니어들과 큰 규모의 애플리케이션들을 개발했습니다. 이 회사는 고객들이 회사들에 피드백을 줄 수 있는 Saas 제품을 만들었습니다. 이 애플리케이션은 자바스크립트로 프론트엔드, 자바로 백엔드 개발이 되었습니다. Small Improvements의 Frontend 초창기 제품은
* 스몰 임프로브먼트(Small Improvements) 
* Frontend -> 프론트엔드

2020-05-24 09:24 UTC, sujinleeme commented on intro.md
> +**Amazon에서 구매하면 디지털 카피를 구할 수 있나요?**
아마존에서 전자책을 구매할 수 있나요?

2020-05-24 09:25 UTC, sujinleeme commented on intro.md
> +Amazon에서 책을 구매했다면, 이 책이 웹사이트에서 이용할 수 있다는 것을 알게 될 것입니다. 이 책은 무료 콘텐츠지만 Amazon을 통해 수익을 창출하기 때문에, 진심으로 여러분들의 지원에 감사하며 [웹사이트](https://www.robinwieruch.de/)에서 가입할 수 있도록 초대하겠습니다. 회원가입 후 Amazon 구매 영수증을 이메일로
Amazon에서 책을 구매했다면, 이 책이 웹사이트에서 이용할 수 있다는 것을 알게 될 것입니다.
-> 아마존에서 구매했다면, 제 웹사이트에서도 이용 가능합니다.

2020-05-24 09:25 UTC, sujinleeme commented on intro.md
> +책을 읽는 사람들과 함께 공유할 수 있는 [슬랙](https://slack-the-road-to-learn-react.wieruch.com/)이 있습니다. 커뮤니티를 통해 도움을 받거나 도움이 필요한 이들에게 도움을 줄 수 있습니다.
책을 읽는 사람들과 함께 공유할 수 있는  -> 독자들과 함께 하는 슬랙을 운영하고 있습니다.

2020-05-24 09:26 UTC, sujinleeme commented on intro.md
> +**이 책에 기여할 수 있나요?**
이 책에 기여할 수 있나요?

2020-05-24 09:47 UTC, sujinleeme commented on intro.md
> +몇년 간, 로빈은 Small Improvements라는 회사에서 뛰어난 팀의 엔지니어들과 큰 규모의 애플리케이션들을 개발했습니다. 이 회사는 고객들이 회사들에게 피드백을 줄 수 있는 Saas 제품을 만들었습니다. 이 애플리케이션은 자바스크립트로 프론트엔드, 자바로 백엔드 개발이 되었습니다.
네 독비루흐 라고 하네요. @yeseulo 이렇게 고쳐주세요.

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +'더 로드 투 리액트'에서는 리액트의 기초를 가르치고 있습니다. 여러분은 복잡한 도구 없이 순수한 리액트만으로 현업 수준의 애플리케이션을 만들 수 있습니다. 이 책은 리액트 설치부터 기초, 서버 배포까지, 리액트 개발 전 과정이 담겨 있습니다. 각 장마다 참조할 만한 읽기 자료 및 실습 예제들을 실었습니다. 이 책을 읽고 난 후, 리액트로 여러분의 애플리
a real-world application에서 real-world 부분을 '실제로 사용할 수 있는' 또는 '실재' 로 표현하면 어떨까요?

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +'더 로드 투 리액트'에서는 리액트의 기초를 가르치고 있습니다. 여러분은 복잡한 도구 없이 순수한 리액트만으로 현업 수준의 애플리케이션을 만들 수 있습니다. 이 책은 리액트 설치부터 기초, 서버 배포까지, 리액트 개발 전 과정이 담겨 있습니다. 각 장마다 참조할 만한 읽기 자료 및 실습 예제들을 실었습니다. 이 책을 읽고 난 후, 리액트로 여러분의 애플리
```diff
- 각 장마다
+ 각 장에는 (또는 장마다)
```

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +본질적으로, 여러분은 쪽수 매기기, 클라이언트와 서버 측 검색 기능을 가진 스크래치 그리고 정렬과 같은 선진화된 상호작용으로부터 여러분의 리액트 애플리케이션을 만드는 법을 배울 수 있습니다. 저는 이 책이 리액트와 자바스크립트에 대한 나의 열정을 포착하길 바라며, 여러분이 시작하는 데 있어서 도움이 되길 바랍니다.
Essentially 를 '본질적으로' 보다 '기본적으로' 로 쓰는게 조금 더 익숙할 것 같아요

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +본질적으로, 여러분은 쪽수 매기기, 클라이언트와 서버 측 검색 기능을 가진 스크래치 그리고 정렬과 같은 선진화된 상호작용으로부터 여러분의 리액트 애플리케이션을 만드는 법을 배울 수 있습니다. 저는 이 책이 리액트와 자바스크립트에 대한 나의 열정을 포착하길 바라며, 여러분이 시작하는 데 있어서 도움이 되길 바랍니다.
좀 더 매끄러운 표현으로 제안해봅니다. 괜찮다면 번역 마무리에 참고해주세요.

```diff
- 본질적으로, 여러분은 쪽수 매기기, 클라이언트와 서버 측 검색 기능을 가진 스크래치 그리고 정렬과 같은 선진화된 상호작용으로부터 여러분의 리액트 애플리케이션을 만드는 법을 배울 수 있습니다. 
+ 기본적으로 쪽수 매기기, 클라이언트 측과 서버 측 검색 기능, 정렬처럼 고급 상호작용을 통해 리액트 애플리케이션을 맨 처음부터 만드는 법을 배웁니다.
```

```diff
- 저는 이 책이 리액트와 자바스크립트에 대한 나의 열정을 포착하길 바라며, 여러분이 시작하는 데 있어서 도움이 되길 바랍니다.
+ 이 책에 리액트와 자바스크립트에 대한 열정을 담았습니다. 여러분이 시작하는 데 도움이 되길 바랍니다.
```

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +몇 년간, 로빈은 Small Improvements라는 회사에서 뛰어난 팀의 엔지니어들과 큰 규모의 애플리케이션들을 개발했습니다. 이 회사는 고객들이 회사들에 피드백을 줄 수 있는 Saas 제품을 만들었습니다. 이 애플리케이션은 자바스크립트로 프론트엔드, 자바로 백엔드 개발이 되었습니다. Small Improvements의 Frontend 초창기 제품은
```diff
- 대규모 애플케이션을
+ 대규모 애플리케이션을
```

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +로빈은 독일 출신 소프트웨어 및 웹 엔지니어이며, 자바스크립트 선생님으로 활동하고 있습니다. 로빈은 컴퓨터 공학 석사 과정을 마친 후, 스스로 계속해서 공부했습니다. 그는 업무 시간과 여가 시간 모두 자바스크립트를 집중적으로 사용하며 스타트업 세계에서 경험을 쌓고, 이는 결과적으로 다른 사람들에게 자바스크립트를 가르치는 열정이 되었습니다.
```diff
- 스타트업 세계에서 경험을 쌓고,
+ 스타트업 세계에서 경험을 쌓았고,
```

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +강의가 여러분에게 유용하다고 생각해서 후원하고 싶다면, [웹사이트](https://www.robinwieruch.de/about)에 방문하여 후원 방법이 나와 있는 페이지를 방문하면 됩니다. 또한, 이 책이 얼마나 도움이 되었는지 독자들에게 효과적으로 알릴 수 있으며, 다른 사람들 또한 웹 개발 실력을 효과적으로 향상시킬 수 있습니다. 다양한 방법으로 후
```diff
- 만드는데
+ 만드는 데
```

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +이 주제에 대해서 지속적으로 가르치고 싶습니다. 온라인에는 최신 업데이트가 잘 되지 않는 자료 혹은 자료가 많지 않은 경우가 종종 있습니다. 하지만 사람들은 보통 꾸준히 자주 업데이트되는 자료로 공부하고 싶어 합니다. 이런 자료를 제공함으로서 여러분들이 꾸준하게 공부하는 경험을 만들어주고 싶습니다. 또한, 어려운 환경에 있는 분들에게 무료로 컨텐츠를 제공
```diff
- 이런 자료를 제공함으로서
+ 이런 자료를 제공하여 (또는 이런 자료를 제공함으로써)
```

2020-05-25 04:02 UTC, yeseulo commented on intro.md
> +* UI 혹은 UX와 같은 디자인을 했었다면, 리액트를 시작하는 데 망설이지 마세요. 이미 HTML과 CSS에 익숙하기 때문에 리액트를 공부하는 데 도움이 될 것입니다. JavaScript 기본기만 좀 더 공부하면, 리액트를 수월하게 배울 수 있습니다. 최근엔 UI/UX가 종종 리액트로 만들어진 구현 과정과 점점 밀접해지기 때문에, UI/UX를 알고 있는
```diff
- UI/UX를 알고 있는 것이 코드가 어떻게 동작하는 알 수 있는 이점이 될 수 있습니다.
+ 코드가 어떻게 동작하는지 아는 것은 이점이 될 수 있습니다.
```

2020-05-28 07:15 UTC, sujinleeme commented on intro.md
> +* 개발팀의 PO(Product Owner) 혹은 PM(Product Manager)이라면 이 책을 통해 리액트 애플리케이션의 필수적인 부분들을 분석할 기회가 될 수 있습니다. 각 장에는 리액트 콘셉트/패턴/기술들이 다른 요소에 더해지고 전체 구조를 발전시키는 내용이 있습니다. 이는 리액트를 전체적으로 이해하는 좋은 설명서가 될 것입니다.
PO(Product Owner) 혹은 PM(Product Manager) 번역해주세요.

2020-06-04 13:21 UTC, sujinleeme requested changes

2020-06-04 13:21 UTC, sujinleeme commented on intro.md
> +* UI 혹은 UX와 같은 디자인을 했었다면 리액트를 시작하는 데 망설이지 마세요. 이미 HTML과 CSS에 익숙하기 때문에 리액트를 공부하는 데 도움이 될 것입니다. 자바스크립트 기본기만 좀 더 공부하면 리액트를 수월하게 배울 수 있습니다. 최근엔 UI/UX가 종종 리액트로 만들어진 구현 과정과 점점 밀접해지기 때문에 코드가 어떻게 동작하는지 아는 것은
최근엔 --> 수정해주세요.

2020-06-04 13:21 UTC, sujinleeme commented on intro.md
> +* 개발팀의 프로덕트 오너(Product Owner) 혹은 프로덕트 매니저(Product Manager)이라면 이 책을 통해 리액트 애플리케이션의 필수적인 부분들을 분석할 기회가 될 수 있습니다. 각 장에는 리액트 콘셉트/패턴/기술들이 다른 요소에 더해지고 전체 구조를 발전시키는 내용이 있습니다. 이는 리액트를 전체적으로 이해하는 좋은 설명서가 될 것입니
프로덕트 오너(Product Owner) 혹은 프로덕트 매니저(Product Manager) 괄호안의 영어를 삭제해주세요.

2020-06-29 11:32 UTC, merged