[v2] react modern/component definition
the-road-to-learn-react/the-road-to-react-korean pull request #37
Opened 2020-04-24 23:10 UTC by constmoon

Component definition 파트 번역해서 올립니다.
리뷰와 피드백 항상 감사합니다.

2020-04-25 04:48 UTC, sujinleeme requested changes
깔끔한 번역 감사합니다

2020-04-25 04:48 UTC, sujinleeme commented on manuscript/react-modern/component-definition.md
> +전달하려는 인수가 1개인 경우에는 괄호를 제거할 수 있습니다. 그러나 인수가 여러 개인 경우에는 반드시 괄호가 필요합니다.
한 개로 수정부탁드려요. 깔끔한 번역 감사해요 :)

2020-04-25 04:50 UTC, sujinleeme commented on manuscript/react-modern/component-definition.md
> +만약 화살표 함수의 내부가 하나의 구문으로 이루어진 경우(화살표 함수에서 반환값만 존재하는 경우), 함수의 **블록(block) 바디**(중괄호)를 제거할 수 있습니다. **간결한(concise) 바디**에서는 암시된 반환문을 포함하므로 반환문을 제거할 수 있습니다.
함수의 중괄호를 제거할 수 있습니다. return 구문을 포함하기 때문에 제거할 수 있습니다. 가 어떨까요

2020-04-25 04:52 UTC, sujinleeme commented on manuscript/react-modern/component-definition.md
> +앞으로 화살표 함수에서 블록 바디를 사용하지 않는 경우에 대해서는 빠르게 넘어갈 것이기 때문에 이 리팩터링 개념을 이해하고 넘어가세요. 물론 우리가 어떤 걸 사용할지는 컴포넌트의 요구 사항에 따라 다릅니다.
앞으로 화살표 함수를 사용할 것이므로 이 개념을 꼭 집고 넘어가야 합니다. 물론 화살표 함수 사용 여부는 여러분의 선택입니다.  가 어떨까요?

2020-04-26 03:42 UTC, constmoon commented
리뷰 반영하여 수정했습니다. 감사합니다.

2020-04-27 06:46 UTC, yeseulo commented on manuscript/react-modern/component-definition.md
> +앞으로 화살표 함수를 사용할 것이므로 이 개념을 꼭 집고 넘어가야 합니다. 물론 화살표 함수 사용 여부는 여러분의 선택입니다.
오타가 있습니다.
```diff
- 꼭 집고 넘어가야 합니다.
+ 꼭 짚고 넘어가야 합니다.
```

2020-04-27 07:11 UTC, yeseulo commented on manuscript/react-modern/component-definition.md
> +만약 화살표 함수의 내부가 하나의 구문으로 이루어진 경우(화살표 함수에서 반환값만 존재하는 경우), 함수의 중괄호를 제거할 수 있습니다. return 구문을 포함하기 때문에 제거할 수 있습니다.
필요한 내용이 누락된 것 같아 수정 이전 버전을 가져왔습니다. 이전에 body를 '본문'으로 번역했었는데요. block body를 '블록 본문'이라고 하면 어떨까요? concise body는 저도 좀 애매하지만 '간략한 본문' 또는 그 원래 의미인 '한 줄로 된 구문' 표현이 어떨지요

```diff
- 만약 화살표 함수의 내부가 하나의 구문으로 이루어진 경우(화살표 함수에서 반환값만 존재하는 경우), 함수의 **블록(block) 바디**(중괄호)를 제거할 수 있습니다. **간결한(concise) 바디**에서는 암시된 반환문을 포함하므로 반환문을 제거할 수 있습니다.
+ 만약 화살표 함수의 내부가 하나의 구문으로 이루어진 경우(화살표 함수에서 반환 값만 있는 경우), 함수의 **블록(block) 본문**(중괄호)를 생략할 수 있습니다. 한 줄로 된 **간략한(concise) 본문**에서는 return 구문을 포함하기 때문에 삭제할 수 있습니다.
```

2020-04-27 14:00 UTC, constmoon commented on manuscript/react-modern/component-definition.md
> +만약 화살표 함수의 내부가 하나의 구문으로 이루어진 경우(화살표 함수에서 반환값만 존재하는 경우), 함수의 중괄호를 제거할 수 있습니다. return 구문을 포함하기 때문에 제거할 수 있습니다.
block body와 concise body에 대한 언급이 누락되었다는 거죠? 
저는 다른 파트 번역에서 concise body를 '간결한 바디'라고 적고 옆에 괄호로 부연설명을 붙였습니다.
시간이 되면 용어를 통일하는 작업도 필요하겠군요...
우선 예슬님 코멘트대로 block body와 concise body에 대한 언급을 추가하겠습니다. 피드백 감사해요!

2020-04-28 08:15 UTC, sujinleeme approved these changes

2020-04-28 08:15 UTC, merged