[v2] 서드 파티 라이브러리
the-road-to-learn-react/the-road-to-react-korean pull request #6
Opened 2020-03-27 07:51 UTC by yeseulo

- 제목의 third party libraries를 '서드 파티 라이브러리' 로 표현했습니다. 영문 병기가 필요할까요?
- fetch, fetch API, headless, axios는 영문 그대로 사용했습니다.
- npm registry는 'npm 레지스트리'로 표현했습니다.
- promise는 '프로미스', method는 '메서드'로 사용했습니다.

2020-03-27 07:53 UTC, yeseulo commented on manuscript/react-modern/third-party-libraries.md
> +이전에는 해커 뉴스 API 요청을 처리하기 위해 브라우저가 제공하는 기본 fetch API를 사용했습니다. 그러나 모든 브라우저, 특히 구형 브라우저는 이 기능을 지원하지 않습니다. 또한 [headless 브라우저 환경](https://en.wikipedia.org/wiki/Headless_browser)에서 애플리케이션 테스트를 시작하면 fetch AP
마지막 문장 중 괄호로 폴리필과 isomorphic fetch를 언급한 부분의 위치가 자연스러운가요?

2020-04-04 09:19 UTC, sujinleeme requested changes

2020-04-04 09:19 UTC, sujinleeme commented on manuscript/react-modern/third-party-libraries.md
> +이전에는 해커 뉴스 API 요청을 처리하기 위해 브라우저가 제공하는 기본 fetch API를 사용했습니다. 그러나 모든 브라우저, 특히 구형 브라우저는 이 기능을 지원하지 않습니다. 또한 [headless 브라우저 환경](https://en.wikipedia.org/wiki/Headless_browser)에서 애플리케이션 테스트를 시작하면 fetch AP
구형 브라우저에서 fetch를 사용할 수 있게 ([폴리필(Polyfill)](링크)를 추가하거나 클라이언트에 동시에 사용가능한 isomorphic-fetch  등 라이브러리를 도입할 수 있습니다만, 이 개념은 본 학습 목표에서 조금 벗어난 부분입니다. 로 수정해주세요.

2020-04-04 09:19 UTC, sujinleeme commented on manuscript/react-modern/third-party-libraries.md
> +한 가지 대안으로는 기본 fetch API를 원격 API에 비동기 요청을 수행하는 [axios](https://github.com/axios/axios)처럼 안정적인 라이브러리로 대체하는 방법이 있습니다. 이번 장에서 라이브러리(이 경우 브라우저 고유 API)를 npm 레지스트리에 등록된 다른 라이브러리로 대체하는 법을 알아봅니다. 먼저 커맨드 라인에서
영어 문장이 조금 이상한 것 같아요.

이번 장에서는 기존 웹 API 대신 npm 라이브러리인 axios를 사용합니다.  로 수정해주세요.

2020-04-09 15:34 UTC, merged