[v2] React modern
the-road-to-learn-react/the-road-to-react-korean pull request #8
Opened 2020-03-27 14:37 UTC by constmoon

이전에 리뷰 해주셨던 react-modern.md의 일부 내용은 해당하는 챕터 md 파일로 옮겼습니다.

- lists.md
- meet-another-react-component.md

두 개를 새로 작업해서 올립니다.

2020-03-27 14:41 UTC, constmoon commented on manuscript/react-modern/lists.md
> +여기서는 하나의 자바스크립트 타입을 다른 타입으로 변환하는 일은 하지 않을 겁니다. 대신에, 리스트의 각 아이템을 렌더링하는 JSX 문법으로 반환합니다.
`JSX Fragment`를 뭐라고 번역해야 할지 고민하다가 `JSX 문법`이라고 약간 뭉뚱그려놓았는데요. 문맥상 JSX의 빈 태그 문법을 이야기하는 것 같은데 어떻게 이걸 전달할지 고민됩니다. 리액트 공식 문서에는 [Fragment 챕터](https://ko.reactjs.org/docs/fragments.html)가 따로 있더라고요. 다른 분들의 의견이 궁금합니다.

2020-03-27 14:44 UTC, constmoon commented on manuscript/react-modern/meet-another-react-component.md
> +## 컴포넌트 분리
**Meet another React Component**를 어떻게 번역할지 고민이 많았는데요... another를 강조한다면 `새로운 컴포넌트 추가`가 될 것 같은데, 내용상 추가보다는 분리에 더 가깝지 않나 싶어서 `컴포넌트 분리`로 번역을 했습니다.

2020-03-28 14:21 UTC, yeseulo commented on manuscript/react-modern/lists.md
> +여기서는 하나의 자바스크립트 타입을 다른 타입으로 변환하는 일은 하지 않을 겁니다. 대신에, 리스트의 각 아이템을 렌더링하는 JSX 문법으로 반환합니다.
실제로 <React.Fragment>로 쓰니까 영문 그대로 사용하면 어떨까요? 단어의 원래 뜻으로 번역한 예도 본 적이 없는 것 같아요.

2020-03-29 13:52 UTC, constmoon commented on manuscript/react-modern/lists.md
> +여기서는 하나의 자바스크립트 타입을 다른 타입으로 변환하는 일은 하지 않을 겁니다. 대신에, 리스트의 각 아이템을 렌더링하는 JSX 문법으로 반환합니다.
리뷰 감사합니다. 저도 Fragment를 강조하는 게 더 맞다고 생각해요. 마침 모던 리액트 파트 뒤쪽에 Fragment를 다루고 있으니 예슬님 의견대로 진행하겠습니다.

2020-03-30 11:04 UTC, sujinleeme requested changes
몇가지 오탈자에 코멘트를 남겼습니다. 수고하셨어요!

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/jsx.md
> +`npm start`  명령어를 실행해 애플리케이션을 시작합니다. 브라우저를 열고 렌더링된 변수가 “Hello React”로 표시되었는지 확인합니다.
따옴표가 `""` 여야 하는데 `“`로 되어 있어요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/jsx.md
> +`htmlFor`, `id`, 그리고 `type` 와 같이 3가지 HTML 속성을 정의했습니다. `id`와 `type`은 기존 HTML에서 익숙하게 봐온 반면, `htmlFor`는 생소할 겁니다. `htmlFor`는 HTML의 `for` 속성을 나타냅니다. 이렇게 JSX로 몇몇 HTML 속성을 나타낼 수 있습니다. 전체 목록은 리액트 공식 문서 중 [‘지
‘지원하는 HTML 속성’ 따옴표를 제거해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/jsx.md
> +HTML 입력 필드 구현에 대한 내용은 뒤에서 다시 다룹니다. 지금은 JSX의 JavaScript로 돌아가겠습니다. 앞서 우리는 문자열을 App 컴포넌트에 표시하기 위해 string 타입의 변수를 정의했습니다. 이 작업은 자바스크립트 개체에도 동일하게 적용될 수 있습니다.
JavaScript를 자바스크립트로 고쳐주세요

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/jsx.md
> +* [리액트 공식 문서 JSX](https://reactjs.org/docs/introducing-jsx.html).
리액트 공식 문서 JSX를 읽어보세요 로 수정해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/lists.md
> +[자바스크립트의 내장 배열 메서드 map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)을 사용하면 리스트에 있는 각 아이템에 접근하고 이들을 새로운 리스트로 반환할 수 있습니다.
자바스크립트 배열 map 메서드로 고쳐주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/lists.md
> +      {/* 여기에서 리스트를 렌더링 해보세요 */}
여기에서 리스트가 렌더링 됩니다로 수정해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/lists.md
> +* [표준 내장 배열 메서드](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/)를 복습해보세요. 특히 map, filter, reduce를 중점으로 보면 좋습니다. 이들은 네이티브 자바스크립트에서도 사용할 수 있습니다.
자바스크립트 배열 메서드로 수정해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/meet-another-react-component.md
> +## 컴포넌트 분리
네. 저도 컴포넌트 분리가 적합한 것 같습니다.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/meet-the-react-component.md
> +이 리액트 컴포넌트는 App 컴포넌트라는 자바스크립트 함수입니다. 일반적으로 **함수 컴포넌트**라고 불리며, 이외의 다른 종류의 컴포넌트는 뒤에서 다시 다룰 예정입니다(나중에 **컴포넌트 종류**를 참조하세요). 또한, App 컴포넌트는 별도의 매개변수를 받지 않습니다(나중에 **props**를 참조하세요). 마지막으로 App 컴포넌트는 JSX라고 하는
또한, 에 ,를 삭제해주세요.

반환합니다 뒤에 마침표가 빠져있어요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/meet-the-react-component.md
> +함수 본문(body)에서 정의된 변수는 함수가 실행될 때마다 매번 재정의될 것입니다. 자바스크립트 함수처럼요.
함수 본문(body)에서 (body)삭제해주세요. 
개인적으로는 '함수 내 정의된 변수 '가 어떨까 싶네요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/requirements.md
> +웹 개발 환경을 갖춰 봅시다. 텍스트 에디터(예: Sublime Text)나 커맨드 라인(Command line, 터미널(terminal)이라고도 함)(예: iTerm), 또는 IDE(Integrated Development Environment, 통합 개발 환경)(예: Visual Studio Code)가 필요합니다. 자세한 방법은 [개발 환경 설정 가
비주얼 스튜디오 코드(Visual Studio Code, VS Code) 로 수정해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/requirements.md
> +이번 실습에서는 *커맨드 라인(command line)*을 사용할 것입니다. *커맨드 라인 도구(command line tool)*, *터미널(terminal)*, *통합 터미널(integrated terminal)*과 같은 용어로도 불립니다. *에디터*, *텍스트 에디터*, *IDE(Integrated Development Environment, 통합
위에 중복되어 괄호 영어를 생략해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/requirements.md
> +추가적으로, 이 책의 예제를 실습하면서 프로젝트를 GitHub으로 관리하는 것을 추천합니다. 어떻게 사용하는지는 [짧은 가이드](https://www.robinwieruch.de/git-essential-commands/)를 참고하세요. GitHub은 뛰어난 버전 관리 기능을 제공하여 어떤 변화가 일어났는지를 추적할 수 있습니다. 또한 나중에 다른 사람들
* 추가적으로 -> 추가로 (, 삭제) 
* GitHub를 깃허브로 수정해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/requirements.md
> +로컬 환경에서 코드 에디터/터미널 또는 IDE를 설정하고 싶지 않다면 온라인 코드 에디터인 [CodeSandbox](https://codesandbox.io/)를 사용할 수 있습니다. CodeSandbox는 온라인으로 코드를 공유하는 데에 유용한 도구이지만, 로컬 환경에 설정하는 것이 웹 애플리케이션을 만드는 다양한 방법을 배우기에는 더 좋습니다. 또한
* 코드샌드박스(CodeSandbox)로 수정해주세요.
* 이후 코드샌드박스(영어 괄호 없애고)로 작성해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/requirements.md
> +시작하기 전에, [node(노드)와 npm](https://nodejs.org/en/)을 설치해야 합니다. 둘 다 앞으로 필요한 라이브러리(노드 패키지)를 관리하는 데 사용됩니다. 이러한 노드 패키지는 라이브러리가 될 수도 있고, 전체 프레임워크일 수도 있습니다. 여기서는 npm(node package manager, 노드 패키지 관리자 명령어)을 통해
노드 패키지 관리자) 명령어 로 수정해주세요.

2020-03-30 11:04 UTC, sujinleeme commented on manuscript/react-modern/requirements.md
> +노드와 npm을 이미 설치한 경우, 최신 버전인지 확인하세요. npm을 처음 사용하거나 다시 설치할 경우, [npm crash course](https://www.robinwieruch.de/npm-crash-course)를 통해 속도를 높일 수 있습니다.
npm crash course 번역해주세요.

2020-03-30 18:40 UTC, constmoon commented on manuscript/react-modern/meet-the-react-component.md
> +이 리액트 컴포넌트는 App 컴포넌트라는 자바스크립트 함수입니다. 일반적으로 **함수 컴포넌트**라고 불리며, 이외의 다른 종류의 컴포넌트는 뒤에서 다시 다룰 예정입니다(나중에 **컴포넌트 종류**를 참조하세요). 또한, App 컴포넌트는 별도의 매개변수를 받지 않습니다(나중에 **props**를 참조하세요). 마지막으로 App 컴포넌트는 JSX라고 하는
@sujinleeme 반환합니다 문장의 마침표를 괄호 뒤에 붙였는데, 괄호 앞에 붙이는 건가요?

2020-03-30 18:49 UTC, constmoon commented
1df39b2: 리뷰 반영하여 수정했습니다

2020-04-02 12:00 UTC, sujinleeme requested changes

2020-04-02 12:00 UTC, sujinleeme commented on manuscript/react-modern/requirements.md
> +시작하기 전에, [node(노드)와 npm](https://nodejs.org/en/)을 설치해야 합니다. 둘 다 앞으로 필요한 라이브러리(노드 패키지)를 관리하는 데 사용됩니다. 이러한 노드 패키지는 라이브러리가 될 수도 있고, 전체 프레임워크일 수도 있습니다. 여기서는 npm(node package manager, 노드 패키지 관리자) 명령어를 통해
node(노드)를 Node.js로 고쳐주시겠어요. 제목도 Node.js와 NPM이 좋을 것 같아요.

2020-04-02 13:17 UTC, constmoon commented on manuscript/react-modern/requirements.md
> +시작하기 전에, [node(노드)와 npm](https://nodejs.org/en/)을 설치해야 합니다. 둘 다 앞으로 필요한 라이브러리(노드 패키지)를 관리하는 데 사용됩니다. 이러한 노드 패키지는 라이브러리가 될 수도 있고, 전체 프레임워크일 수도 있습니다. 여기서는 npm(node package manager, 노드 패키지 관리자) 명령어를 통해
23573d2: 리뷰 반영하여 수정했습니다! @sujinleeme

2020-04-04 09:10 UTC, merged

2020-04-04 09:11 UTC, sujinleeme commented on manuscript/react-modern/requirements.md
> +시작하기 전에, [node(노드)와 npm](https://nodejs.org/en/)을 설치해야 합니다. 둘 다 앞으로 필요한 라이브러리(노드 패키지)를 관리하는 데 사용됩니다. 이러한 노드 패키지는 라이브러리가 될 수도 있고, 전체 프레임워크일 수도 있습니다. 여기서는 npm(node package manager, 노드 패키지 관리자) 명령어를 통해
@constmoon 감사합니다. 머지 했어요. 🚀

2020-04-15 15:34 UTC, yeseulo commented on manuscript/react-modern/lists.md
>  ~~~~~~~
제가 한 것에서 주석 번역 빠뜨린 것 찾다가 발견했어요. 아랫줄의 주석 `don't do this`도 번역이 필요할 것 같습니다.